### ISSUE TITLE
Design suggestions

### ISSUE THREAD

**Issue by rsnodgrass** [tomvanswam/compass-card#14]
Thrilled that someone built a working compass!!   I started to build a similar compass card a few weeks back, but didn't have time to dig into why it wasn't displaying properly.

A few suggestions:

* I feel like the wind speed is the most important data—and actionable by the user—as opposed to the wind direction. I'd suggest allowing user specification of the larger data point in the ring, and have the direction smaller and somewhere else (after all the direction is already on the arrow on the ring).

* Visually, I'd suggest adding a small N to the top of the ring to indicate North. Small detail, but ties this all together.
 
* Here is a similar compass from Ambient Weather.  I like that this can cleanly display optional data like maximum gust wind speed for the day.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2199132/90119252-2fd52580-dd0e-11ea-94e9-e502ea2018e5.png">

**Comment by tomvanswam** [comment]
I have to thank you, because I got the idea for the card while having a look at your windcompass repo.

They are all good suggestions, I already thought of the possibility to select a different type of indicator 
- arrow inwards (wind)
- arrow outwards (e.g. lightning location see screenshots in #10)
- circle (e.g.for sun/moon)

And you're right, the direction is already made visible by the indicator, so it could be a lot less in your face and make space for other usefull info.

Consider this added to the wish/todo list

/offtopic, as the devcontainer in the repo is not working for me anymore, I cannot easily develop at this moment. Somehow the container is running, open ports for a develop home assistant instance, but the browser on my host throws a `ERR_CONNECTION_REFUSED`
When I get this fixed I can work on the wishlist again.

**Comment by tomvanswam** [comment]
Not all imporvements done yet...

**Comment by kzim200** [comment]
Thanks for the card! 
A suggestion is that the arrow changes colors according to user-set wind speeds, like in bar-chart, and big number card.

Thanks again.

**Comment by tomvanswam** [comment]
> Thanks for the card!
> A suggestion is that the arrow changes colors according to user-set wind speeds, like in bar-chart, and big number card.
> 
> Thanks again.

Issue #12 covers this. As this is a bit more work, it will take a bit longer to implement.

**Comment by tomvanswam** [comment]
More design suggestions [here](https://community.home-assistant.io/t/compass-card-points-you-in-the-right-direction/217909/69?u=tomvanswam).
