### ISSUE TITLE
Compass size on small cards

### ISSUE THREAD

**Issue by yuvalabou** [tomvanswam/compass-card#44]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
Comapss size is excceeding the borders when placed inside horizontal stack.
![image](https://user-images.githubusercontent.com/3170485/97711553-e8b53000-1ac5-11eb-846e-da85d0367068.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tomvanswam** [comment]
The compass does not scale, this is by design.

Currently I don't know how to scale it, so I need to figure that out in order to make that work.
It's not easy to make the scaling work, as the texts inside the compass should scale too, otherwise it will look wrong as well.

As this is a known 'limitation' I'm changing the label to enhancement.

**Comment by tomvanswam** [comment]
Please note that only the compass + indicators scale. The texts do not.

**Comment by Lampyridae1984** [comment]
I recommend temporarily using card-mod. Here's the base code:

```
card_mod:
  style: |
    ha-card {
      transform: scale(1.0,1.0) translate(0%,0%);
      aspect-ratio: 1 / 1;
    }
    div {
      transform: scale(1.0,1.0) translate(0%,0%);
    }
```

**_ha-card_** is of course for the outer part of the card and **_div_** is the inner part (basically the actual compass). The **_aspect ratio_** value helps to conform the card to other cards, for example when using grid cards. The **_translate_** value moves the compass within the card, so that it can be centered. Not sure how well this works across different browsers and platforms, but there are compatible workarounds available online.
